### ISSUE TITLE
How can I set invalid before token expired?

### ISSUE THREAD

**Issue by herb123456** [paragonie/paseto#100]
Hello

This is a very nice project, and I'm considering to switch from JWT.

I know JWT also doesn't have this feature, But I want to know paseto project can support "set token invalid before expired" feature now? or in the future?

thx.

**Comment by panva** [comment]
The tokens are self-contained, the only mechanism both paseto or jwt consumers have is to blacklist the token’s jti with the token’s exp as the timestamp to drop this blacklist entry.

**Comment by paragonie-security** [comment]
It looks like this question was answered, so I'm going to close it. Please let me know if that's in error.
