### ISSUE TITLE
Duplicate php function documentation

### ISSUE THREAD

**Issue by chocolatkey** [paragonie/paseto#105]
In the Util.php file, while figuring out how to work with the jti in the footer, I found functions with duplicate phpdoc descriptions that do not perform the same operations:

https://github.com/paragonie/paseto/blob/master/src/Util.php#L138

https://github.com/paragonie/paseto/blob/master/src/Util.php#L157

https://github.com/paragonie/paseto/blob/master/src/Util.php#L177

**Comment by paragonie-security** [comment]
This will be fixed in #128 once #127's design is finalized.
