### ISSUE TITLE
Maybe wrong documentation ? 

### ISSUE THREAD

**Issue by BruceGitHub** [paragonie/paseto#110]
I decided to use paseto and I starting to read the docs 
but this seems to have an error

[https://github.com/paragonie/paseto/tree/master/docs](https://github.com/paragonie/paseto/tree/master/docs)
```php
php

/**
 * @var SymmetricKey $sharedKey
 */
$token = Builder::getLocal($sharedKey, new Version2());

$token = (new Builder())
    ->setKey($sharedKey)
....
```

in fact is missing the variable

```
$sharedKey = new SymmetricKey(random_bytes(32));
```
in both example

**Comment by paragonie-security** [comment]
The documentation does not have key management in scope. You could generate it randomly, but doing so will make tokens un-decryptable after the page has loaded. That's not very useful.

**Comment by BruceGitHub** [comment]
Right, but I was referring only in the case of copy and paste to try something with the lib
