### ISSUE TITLE
Exception codes

### ISSUE THREAD

**Issue by razvanioan** [paragonie/paseto#116]
Is there a way to implement exception codes, at least for Parser ?

For instance `Parser` can throw a number of Exception types (which we can distinguish quite well) but we don't want to directly show the default error messages to the user, and for sure not all those error types.

For instance, I would like to show a message to the user ONLY if it didn't pass the NotExpired rule.

I get a `RuleViolation` exception with some info in the message that I need to parse and reinterpret to the user.

A fixed custom code would have been more precise.

**Comment by paragonie-security** [comment]
This is doable.

**Comment by paragonie-security** [comment]
We'll do this after we're done with the other work we have in the pipeline.
