### ISSUE TITLE
Project stalled

### ISSUE THREAD

**Issue by Slamdunk** [paragonie/paseto#117]
Hi @paragonie-scott @paragonie-security @paragonie-staff this library seems a bit stalled.

I'd like to contribute more (see #111), but need at least a feedback per month to consider efforts worthy.

Would you consider adding more maintainers, at least for basic maintenance such as PHP version upgrades, tools updates, etc?

**Comment by paragonie-security** [comment]
There's a lot of work happening behind the scenes. v3/v4 will be a thing before the end of the year.

**Comment by djmarland** [comment]
Any news on this? I was looking into updating to PHP 8 but this library still requires 7 at the moment.
