### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by stayallive** [paragonie/paseto#123]
Hi there,

We are using Paseto instead of JWT in our application but we noticed that this library is not yet ready for PHP 8 and also saw no current work on this so I wanted to check in if behind the scenes there is work ongoing and if we can expect a PHP 8 release in the near future or that we need to have a little more patience.

Thanks 👍

**Comment by paragonie-security** [comment]
#124 will add PHP 8 support

**Comment by stayallive** [comment]
With the release of [1.1.0](https://github.com/paragonie/paseto/releases/tag/v1.1.0) I think we can safely considered this closed, thanks a bunch!
