### ISSUE TITLE
Class \"ParagonIE\\Paseto\\Protocol\\Version4\ Not found

### ISSUE THREAD

**Issue by GTS-MEGHNI** [paragonie/paseto#149]
It seems I can't find the Version4 class in a new installation via composer

**Comment by paragonie-security** [comment]
That's odd. Did you run the `php composer.phar install` command first? If so, did it spit out an error message?

**Comment by GTS-MEGHNI** [comment]
> That's odd. Did you run the `php composer.phar install` command first? If so, did it spit out an error message?

I did install the package through composer require paragonie/paseto. After the installation I check the path vendor\paragonie\paseto\src\Protocol I foundd only Version 1 and Version 2 in this directory

**Comment by paragonie-security** [comment]
Did you install version 1 or version 2 of the library?

**Comment by GTS-MEGHNI** [comment]
I didn't specify the version in the command line, it should get me latest version no ?
