### ISSUE TITLE
Undefined array key "ParagonIE\Paseto\Keys\SymmetricKey"

### ISSUE THREAD

**Issue by oojacoboo** [paragonie/paseto#170]
Looks like there is a namespace change and inconsistency in 3.1.0 between the `$key` class being passed in and the expected array key.

```
Undefined array key "ParagonIE\Paseto\Keys\SymmetricKey" in /srv/www/vendor/paragonie/paseto/src/Purpose.php:154
```

**Comment by paragonie-security** [comment]
Fixed in v3.1.1

Thanks for reporting this!
