### ISSUE TITLE
v4: read claims of an expired token

### ISSUE THREAD

**Issue by razvanioan** [paragonie/paseto#172]
I see that there is no way to read claims of an expired token anymore (I could do that in v2).
There are some cases I need the embedded info even if token is not valid anymore.

**Comment by razvanioan** [comment]
Ah, I can use the parse with true for skipValidation parameter
Nevermind

**Comment by paragonie-security** [comment]
You can.

https://github.com/paragonie/paseto/blob/master/src/Parser.php#L663-L666

https://github.com/paragonie/paseto/blob/master/src/Parsing/NonExpiringSupport.php#L7-L20
