### ISSUE TITLE
[V1] Vulnerability flag due to phpseclib/phpseclib < 3

### ISSUE THREAD

**Issue by NaterTots** [paragonie/paseto#173]
Details on vulnerability:
https://github.com/advisories/GHSA-jpr7-q523-hx25

New version of phpseclib/phpseclib:
https://github.com/phpseclib/phpseclib/releases/tag/3.0.34

**Comment by paragonie-security** [comment]
The CVE in phpseclib doesn't affect us.

**Comment by paragonie-security** [comment]
Closing for the following reasons:

* Version 3.x of our library removed Protocol v1 and v2 support. We recommend upgrading to library v3.x.
* Protocol v1 support didn't use the vulnerable code in phpseclib, so even if you cannot upgrade yet, you are not impacted.
