### ISSUE TITLE
Structured payloads to avoid key collisions

### ISSUE THREAD

**Issue by eropple** [paragonie/paseto#19]
Right now, the payload, as defined, seems to have only one key, `exp`. It seems like, somewhere and somewhen, somebody is going to try to stick a colliding key into the payload. Also, down the line, it strikes me that there may be additional metadata to add to the token (which could cause forward-upgrade issues for users with colliding keys). Maybe it'd be better for the basic payload structure to be:

```
{
  "exp": <expiry>,
  "d": <any legal JSON token>
}
```

For ease of use this could be constrained such that `d` must be a JSON object (in particular that'd probably make static-language implementations a little bit easier).

Thoughts?

**Comment by paragonie-scott** [comment]
I suspect this may be a documentation issue, which has hopefully been resolved since January. Please feel free to correct me if I'm mistaken.
