### ISSUE TITLE
Naming issue

### ISSUE THREAD

**Issue by phaza** [paragonie/paseto#28]
I really like this initiative, so we can get rid of pesky JWT.
Although I probably don't understand all the dangers, I know there are some, which make me uncertain even if I were to do JWT seemingly done right :/

And although I really like the name itself, the usability of the acronym is really bad. It's more or less impossible to search for. Is there any chance of an acronym change?

I don't have any good suggestions off the top of my head, but I'm willing to put some effort into it if you're open to an acronym change of some sort?

**Comment by paragonie-scott** [comment]
> Is there any chance of an acronym change?

Very much yes. I went with "PAST" because I struggled and ultimately failed to think of something clever.

**Comment by paragonie-scott** [comment]
What if we renamed this to Paseto? (PASeTo) It's far more Googleable.

**Comment by SlvrEagle23** [comment]
what about SEXTANT

Secure, EXtensible, Tech-Agnostic, Nifty Tokens

has kind of a nautical vibe to it, and appears largely unoccupied :P

**Comment by paragonie-scott** [comment]
I really like SEXTANT as a name.

I'm going to go with Paseto simply because it minimizes the change necessary (same name, just different acronym) but is distinguishable on Google.

If @tqbf et al. are serious about a Web Token Competition, I hope someone uses it for their entry. It's a good one.

**Comment by paragonie-scott** [comment]
I'm ***very ironically*** running into the naming issue trying to search for other implementations of PAST (e.g. Python) to let repository owners know about the new acronym. I think this is an overwhelmingly positive idea.

**Comment by phaza** [comment]
Good call, I like the name!
