### ISSUE TITLE
Paseto can be use is production ?

### ISSUE THREAD

**Issue by Ducatel** [paragonie/paseto#29]
Hi,

I just finish to read your post about JWT security issues.
Now I need to plan to migrate my code from JWT to another solution.

I saw you made 3 Pre-release, but you set your version `0.3.0` as `stable`.
So I don't know if you consider PAST production ready.

PAST isn't stable/secure enough to be use in production ?

Thanks for your work ;)

**Comment by paragonie-scott** [comment]
The releases are marked as pre-release on this page: https://github.com/paragonie/past/releases

The icon on the front page is confusing. They default to the latest release as "stable", even if the project isn't. That's kind of unfortunate, but that's how Travis CI interprets the releases.

**Comment by Ducatel** [comment]
OK, so I understood well.
Do you have any idea of when the first release will come ?

**Comment by paragonie-scott** [comment]
Probably soon. I was going to hold off on the results of a hypothetical Web Token Competition before tagging v1.0.0, but that might not be worth awaiting.

**Comment by Ducatel** [comment]
Ok nice ;)
I will way for that.
There is a Web Token Competition ? I never heard about it ;).

**Comment by paragonie-scott** [comment]
Yeah, a few cryptography experts were spitballing a hypothetical Web Token Competition. I tried to get the ball rolling, but the only people who put much time into this were myself and @bascule, and our professional relationship isn't exactly competitive.

**Comment by Ducatel** [comment]
Ok, good luck for that competition. 
I'm not an expert in cryptography  so I cannot help you  . :yum:

I saw you release the `v0.5.0`. Paseto still cannot be use in prod ?

Ps: You made a mistype in the release: `Verison 0.5.0` --> `Version 0.5.0` :wink:

**Comment by paragonie-scott** [comment]
The only changes foreseen between now and v1.0 are documentation related.

**Comment by Ducatel** [comment]
Ok, nice.
So I will start to migrate from JWT to Paseto 😜
