### ISSUE TITLE
OAuth2 Implementation 

### ISSUE THREAD

**Issue by Alofoxx** [paragonie/paseto#5]
Can you see if Paseto can be used for OAuth2 to replace \OAuth2\ResponseType\JwtAccessToken

There was also desire to have customization https://github.com/bshaffer/oauth2-server-php/pull/795#issue-199776010

**Comment by paragonie-scott** [comment]
If OAuth2 / OpenID Connect will not accept a JWT alternative unless it has an Internet Standard RFC attached to it, this might be a non-starter. Although we have a draft RFC on-hand, it's unlikely to ever be accepted.

**Comment by paragonie-scott** [comment]
Disregard that, apparently that doesn't matter for OAuth.

**Comment by paragonie-security** [comment]
Moving to https://github.com/paseto-standard/paseto-spec/issues/15
