### ISSUE TITLE
Examples are wrong?

### ISSUE THREAD

**Issue by aidantwoods** [paragonie/paseto#50]
So I thought I'd add an example from the readme to my test suite, and it turns out there are some typos (unless of course my implementation is somehow completing words and changing a year ;p)

![screen shot 2018-03-08 at 19 00 44](https://user-images.githubusercontent.com/3288888/37170626-3e6ac78e-2303-11e8-9741-8695ce40fdc7.png)

I think `"exp":` should be `"expires":` and the year should be `2019` instead of `2039`.

([correct example](https://github.com/aidantwoods/swift-paseto/commit/c5647b91c8a99a0082c2998596e1df764f5e2f67))

I would have opened this as a PR, but I wanted to check whether the second example also has the same problem. It appears to, but I can't conclude this because there isn't a public key available to verify the message ;-) (this is a request to add the public key to the readme)

**Comment by paragonie-scott** [comment]
I think it's a matter of me updating one but not the other. Good catch. :)

**Comment by paragonie-scott** [comment]
I'll have this fixed tonight.

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/paseto/commit/d2f8902738486d1308a09197202be36c4d4ff6f8 -- I included a unit test so we can copy/paste tokens and then verify their correctness if the README is ever changed.

**Comment by aidantwoods** [comment]
Good call on adding the unit tests too 👍
