### ISSUE TITLE
extract php implementation and specification from the repository

### ISSUE THREAD

**Issue by Grummfy** [paragonie/paseto#78]
Hello,
I think for a readability of the project, it could be very helpfull to split the specification of paseto and the implementation in php. It allow people to see to evolution of the spec and the implemntation without any missmatch.

thanks

**Comment by peter-evans** [comment]
I think this is a good idea. It might also be nice to have the official test vectors listed separately in a way that is language independent.

**Comment by peter-evans** [comment]
Just noticed that the official test vectors are listed at the end of the RFC.

**Comment by paragonie-scott** [comment]
As time goes on, the more I see this change as desirable. Consider it done when I have a moment to work on PASETO again (which will be soon).

**Comment by paragonie-security** [comment]
We will be moving the specification to a repository under https://github.com/paseto-standard as soon as #127 is complete.

**Comment by paragonie-security** [comment]
https://github.com/paseto-standard/paseto-spec

**Comment by purificant** [comment]
It's great to see spec in it's own repo. This means you can now include the spec in your library as a git submodule or subtree and get access to test vectors JSON.
