### ISSUE TITLE
Online tool on paseto.io

### ISSUE THREAD

**Issue by Extarys** [paragonie/paseto#80]
Yo should make possible to use paseto on your website (like JWT does).
It would be great!

**Comment by davidperrenoud** [comment]
Browser support for PASETO validation/decoding is planned: https://github.com/sjudson/paseto.js/issues/9#issuecomment-440810893. When that is available, it should be easy to implement an online tool for public tokens.

**Comment by paragonie-security** [comment]
https://github.com/paragonie/paseto-io  :)
