### ISSUE TITLE
Inconsistent use of 'expires' and 'exp' in tests.

### ISSUE THREAD

**Issue by mjpieters** [paragonie/paseto#84]
There are two instances of `'expires'` in the `Version2VectorTest` tests:

* https://github.com/paragonie/paseto/blob/fa662c687f6dcdc3ae177ca3bdcae405cf6d6d89/tests/Version2VectorTest.php#L226
* https://github.com/paragonie/paseto/blob/fa662c687f6dcdc3ae177ca3bdcae405cf6d6d89/tests/Version2VectorTest.php#L286

Everything else uses `'exp'`. Should these be altered for consistency?

**Comment by paragonie-scott** [comment]
👍 Yes, we should use `exp` here.
