### ISSUE TITLE
Duplicate test vector name

### ISSUE THREAD

**Issue by mjpieters** [paragonie/paseto#85]
I found some test names that have been re-used, probably in error:

* There are two `'Test Vector S-6'` entries in the Vector2VectorTest tests file. Should the second, which adds a non-empty footer to the first test, be renamed to S-7?

  See: https://github.com/paragonie/paseto/blob/fa662c687f6dcdc3ae177ca3bdcae405cf6d6d89/tests/Version2VectorTest.php#L286-L297

* There is a signing test that re-uses a name from an encryption test. It should probably be renamed.

  See: https://github.com/paragonie/paseto/blob/fa662c687f6dcdc3ae177ca3bdcae405cf6d6d89/tests/Version2VectorTest.php#L299-L305

  This is probably a copy-and-paste error when the [corrensponding encryption test](https://github.com/paragonie/paseto/blob/fa662c687f6dcdc3ae177ca3bdcae405cf6d6d89/tests/Version2VectorTest.php#L234-L241) was re-used.  I think it should be named S-8 instead.

**Comment by paragonie-scott** [comment]
Good catch.
