### ISSUE TITLE
Official logo

### ISSUE THREAD

**Issue by peter-evans** [paragonie/paseto#91]
Would be great to have an official PASETO logo. I know from a technical standpoint PASETO speaks for itself, but for whatever reason having a logo does seem to give projects a greater sense of credibility. I think something as simple as that would help to grow the community.

**Comment by paragonie-scott** [comment]
This is a good suggestion.

I hadn't put any thought towards what a logo might look like, but if you (or anyone, really) has any suggestions, I know a few artists who would probably do a phenomenal job at rendering these ideas and some of them are probably available for work soon.

**Comment by peter-evans** [comment]
I don't have any good suggestions for the design but perhaps if we gave the artists a short brief or list of keywords they might be able to come up with some designs.

For reference, this blog post explains a bit about how they came up with the design for the JWT logo.
https://auth0.com/blog/jwt-json-webtoken-logo/

**Comment by paragonie-security** [comment]
We still intend to do this, but thinking of a clever design is hard, and not really our skillset.

**Comment by paragonie-security** [comment]
Moving to https://github.com/paragonie/paseto/issues/91
