### ISSUE TITLE
ReferenceError: cb is not defined

### ISSUE THREAD

**Issue by joseramongravity** [paragonie/paseto#97]
Error happens on macOs when trying to generate the token
```
ReferenceError: cb is not defined
    at encoder.encrypt (/Users/.../server/src/utils.js:556:16)
    at /Users/.../server/node_modules/paseto.js/lib/utils.js:239:39
    at sodium.ready.then (/Users/.../server/node_modules/paseto.js/lib/protocol/V2.js:146:14)
```

Edit:
This happens when i try to use something that is not the callback function
`Error: Failed to construct 'TextDecoder': the 'fatal' option is unsupported.`

I will move this to the Paseto.js

**Comment by SecurityInsanity** [comment]
This looks to be a problem with the javascript version of Paseto, which is located: [HERE](https://github.com/sjudson/paseto.js) not the PHP version (at least according to the stack trace), do you also run into problems with the PHP Version?

**Comment by joseramongravity** [comment]
Havent tested the PHP Version
